### ISSUE TITLE
Short pulse, Long Pulse and Persistent command not implemented

### ISSUE THREAD

**Issue by FernandoMK** [Fraunhofer-FIT-DIEN/iec104-python#12]
I believe the QU field of Qualifier of Command (QOC) is not implemented. Is there any way to send a command with Short Pulse, Long Pulse, or Persistent QU for SCO, DCO, and RCO types?

**Comment by m-unkel** [comment]
That's right, but we can implement the feature.

**Comment by m-unkel** [comment]
There it is: https://github.com/Fraunhofer-FIT-DIEN/iec104-python/tree/feature-qualifier-of-command
I will do some test and create a new 1.18 release asap.

**Comment by m-unkel** [comment]
Version 1.8.0 has been released. Please provide feedback on whether the issue has been resolved.

**Comment by FernandoMK** [comment]
I ran some tests and everything worked correctly. I greatly appreciate the update. Thank you Martin!
