### ISSUE TITLE
Add option to use Select or Execute in Qualifier of Command

### ISSUE THREAD

**Issue by FernandoMK** [Fraunhofer-FIT-DIEN/iec104-python#2]
When trying to send a Single Command (C_SC_NA_1) from an IEC104 client to a slave device, an error occurs because the command has the QOC's S/E field set to "execute" (value 0).

Therefore, it is necessary to send the command with the QOC's S/E field set to "select" (value 1), and then send the same command with "execute".

Below are images collected through Wireshark.

The first images displays the packets for the execution of a Single Command (C_SC_NA_1) using the TestHarness software from Triangle Microworks. In it, you can observe the sending of an ASDU of type C_SC_NA_1 with COT = ACT and S/E = Select. Subsequently, the slave responds with ACTCON.
![wireshark - iec104 - testharness - 1](https://github.com/Fraunhofer-FIT-DIEN/iec104-python/assets/56979826/fe3a125a-5227-43de-97b1-30a363f92322)

After the Select, the same command is sent again with COT = ACT and S/E = Execute. The slave responds with ACTCON as expected.
![wireshark - iec104 - testharness - 2](https://github.com/Fraunhofer-FIT-DIEN/iec104-python/assets/56979826/0dedab87-f361-4c70-913f-f4125e5e407d)

Following that, you can verify the correct writing of the value to the slave device.

The next images show the same command being sent through the IEC104 Python client built with this library. It can be seen that when sending a command, only the command with the S/E = Execute field is sent, missing the Select part before. Therefore, the slave responds with ACTCON_NEGA, and the sent value is not updated on the slave device.
![wireshark - iec104 - python client](https://github.com/Fraunhofer-FIT-DIEN/iec104-python/assets/56979826/09b79bb0-7780-431c-9eb6-855ecec7ef3f)

Because of this, the value sent by the client is never updated on the slave device.

**Comment by m-unkel** [comment]
Thank ypu for the detailed report.

I can confirm that iec104-python is not sending commands with the select flag.
I will prepare a fix.

**Comment by lennart-bader** [comment]
From my understanding, this should be an optional feature depending in the desired operation mode (direct vs. select and execute). Is this correct?

**Comment by FernandoMK** [comment]
> From my understanding, this should be an optional feature depending in the desired operation mode (direct vs. select and execute). Is this correct?

Hello Lennart Bader, thank you for the comment.

Based on my knowledge of the protocol, IEC60870-5-104, commands (whether Single or Double Commands) and set-points always have the field for Select/Execute. There is no such thing as "Directly."

**Comment by lennart-bader** [comment]
For command transmission, IEC104 specifies two standard procedures according to [this technical report (page 22)](https://www.fit.vut.cz/research/publication-file/11570/TR-IEC104.pdf):
* "Direct command": Control operations are immediately executed (The "execute" flag is set for the first command, as currently implemented)
* "Select and execute command": Two step command, where first the "select" flag is set, the operation is checked by remote station (but not yet executed) and then acknowledged (or not acknowledged) to the client. The client can then send the same command with the "execute" flag to actually instruct the remote station to execute the command

So just sending the "execute" flag is still according to standard, and I guess the "select & execute" mode is missing.

**Comment by FernandoMK** [comment]
> For command transmission, IEC104 specifies two standard procedures according to [this technical report (page 22)](https://www.fit.vut.cz/research/publication-file/11570/TR-IEC104.pdf):
> 
> * "Direct command": Control operations are immediately executed (The "execute" flag is set for the first command, as currently implemented)
> * "Select and execute command": Two step command, where first the "select" flag is set, the operation is checked by remote station (but not yet executed) and then acknowledged (or not acknowledged) to the client. The client can then send the same command with the "execute" flag to actually instruct the remote station to execute the command
> 
> So just sending the "execute" flag is still according to standard, and I guess the "select & execute" mode is missing.

You are correct. Based on this document and the IEC60870-5-101 standard (chapter 7.4.7), there is indeed a direct command mode that simply sends the execute flag. I apologize for my earlier misconception.

**Comment by FernandoMK** [comment]
I'm working on a fix from a fork as well. I noticed that when running the test.py file located in "tests," the following exception occurs.

```
------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\...\iec104-python\tests\test.py", line 345, in <module>
    if sv_step_point.read():
ValueError: Cannot send read commands as server
```

Is the test suite broken, or is this an expected behavior?

**Comment by m-unkel** [comment]
There is a typo, yes, please see branch fix-tests, I will merge it soon.

Here is a suggestion for the command mode feature:
https://github.com/Fraunhofer-FIT-DIEN/iec104-python/tree/feature-command-mode

**Comment by m-unkel** [comment]
Can you verify that this will fix your problem?
pip install git+https://github.com/Fraunhofer-FIT-DIEN/iec104-python.git@feature-command-mode

**Comment by FernandoMK** [comment]
> Can you verify that this will fix the issue? pip install git+https://github.com/Fraunhofer-FIT-DIEN/iec104-python.git@feature-command-mode

I tested this new version using the SELECT_EXECUTE flag. I tested it for the following commands: C_SC_NA_1, C_DC_NA_1, C_SE_NB_1, and C_SE_NC_1. All of them worked correctly.

However, the read command `point.read()` stopped working and is always returning `False`. In Wireshark, I noticed that the read command (C_RD_NA_1) was sent, and a valid response from my slave device was also sent, but the `point.read()` command still returns `False`.

Below is the Wireshark screenshot showing the C_RD_NA_1 command sent and the M_ME_NB_1 response being sent by the slave to the client.

![wireshark - iec104 - python client - 2](https://github.com/Fraunhofer-FIT-DIEN/iec104-python/assets/56979826/cdaab209-382f-4f4d-b447-1226092756d4)

> There is a typo, yes, please see branch fix-test, I will merge it soon.

About this, the branch fix-test is up to date with main. Are there any commits left to push in your local repository?

**Comment by m-unkel** [comment]
> However, the read command `point.read()` stopped working and is always returning `False`. In Wireshark, I noticed that the read command (C_RD_NA_1) was sent, and a valid response from my slave device was also sent, but the `point.read()` command still returns `False`.

A pushed a fix into the feature branch.

> About this, the branch fix-test is up to date with main. Are there any commits left to push in your local repository?

Oh sorry, i pushed the missing commit.

**Comment by coop-open-source** [comment]
The update was released to PyPI

**Comment by FernandoMK** [comment]
Just letting you know, it seems that the automatic documentation from Sphinx has stopped working. The C++ Core section is okay, but the c104 Python module has no documentation on classes, methods, properties, and enums.

This is the C++ Core section:
![iec104 c++ docs](https://github.com/Fraunhofer-FIT-DIEN/iec104-python/assets/56979826/e978d3a4-1e00-4b5d-8bd8-20462f3ef91c)

This is the c104 python module section (everthing is like that):
![iec104 python module docs](https://github.com/Fraunhofer-FIT-DIEN/iec104-python/assets/56979826/3b0acc70-3970-4b70-a5ec-7e443f387a83)

Is everything ok with the documentation?

**Comment by FernandoMK** [comment]
I also noted that the C_SE_NA_1 commands were not fixed with the SELECT_AND_EXECUTE command mode. I opened a pull request with the correction. Just a simple fix :)

**Comment by coop-open-source** [comment]
thanks I merged your contribution!
I will create a 1.17.1 once the documentation generation is fixed..

**Comment by m-unkel** [comment]
release 1.17.1 is there
