### ISSUE TITLE
Simple client example with AttributeError

### ISSUE THREAD

**Issue by martinscheu** [Fraunhofer-FIT-DIEN/iec104-python#21]
Hello
When I run the example simple_client.py I get a 
`
    if command.transmit(cause=c104.Cot.ACTIVATION):
       ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'transmit'
`
I couldn't run other commands neither, like C_SC_NA_1 or C_SE_NA_1.

Thank you for the support.

**Comment by m-unkel** [comment]
Closed due to missing response.
