### ISSUE TITLE
Error on raspbian ARMv7

### ISSUE THREAD

**Issue by mauricemullens** [Fraunhofer-FIT-DIEN/iec104-python#4]
using import c104 produces this error:

.venv/lib/python3.7/site-packages/c104.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: __atomic_load_8

Any idea how to fix this?

**Comment by mauricemullens** [comment]
I build it from source, since i got a not found on the binary release

**Comment by m-unkel** [comment]
You are right! And you build it on the same raspberry where it throws the error message?

**Comment by m-unkel** [comment]
I am able to reproduce the issue and i am working on a fix.

**Comment by mauricemullens** [comment]
Fantastic! Thanks a lot

**Comment by m-unkel** [comment]
the bug should be fixed in 1.17.1
