### ISSUE TITLE
iec104-python documentation site not working properly

### ISSUE THREAD

**Issue by bozyman3000** [Fraunhofer-FIT-DIEN/iec104-python#6]
All chapters related to iec104-python lib in docs are empty - [https://iec104-python.readthedocs.io/python/index.html](url)

![image](https://github.com/Fraunhofer-FIT-DIEN/iec104-python/assets/66666366/e569ea89-8ff7-412c-a1b0-2d0e58b486fc)

**Comment by m-unkel** [comment]
thank you, I am working on a fix

**Comment by m-unkel** [comment]
should be fixed

**Comment by bozyman3000** [comment]
Thank you for prompt resolution! 🙂
